version: '3.8'

services:
    db:
        image: mysql:8.0
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 127.0.0.1:3306:3306
        restart: always
        networks:
            
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: always
        volumes:
        networks:
            - symfony_db_net
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: always
        volumes:
        ports:
            - 80:80
        networks:
volumes:

networks: